UI: Simplify Auto Config / Settings for Caffeine
caffeinetv/obs-studio pull request #14
Opened 2019-01-02 05:13 UTC by Andersama

Edits the auto configuration wizard to take some additional settings from the plugin.

Note: Does make use of changes to libobs, and uses the properties view. The properties view is being
removed for services in regular OBS, so these edits will be moot in the near future.

2019-01-04 02:37 UTC, cogwheel requested changes
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/14)* status: 7 of 10 files reviewed, 12 unresolved discussions (waiting on @Andersama and @cogwheel)

___
*[plugins/caffeine/caffeine-output.c, line 1095 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVL_yqn-rt_Yeq2cWec:-LVL_yqoEah6jSFPetaJ:b-o4e5lf) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-output.c#L1095)):*
> ```C
> }
> 
> static struct resolution {
> ```

Since this struct is being produced by plugins and consumed by the UI module, this should be declared in one of the shared headers (probably obs-output.h).
___
*[plugins/caffeine/caffeine-output.c, line 1097 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVL_CggEOIM0yRNpspe:-LVL_CggEOIM0yRNpspf:bdql55k) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-output.c#L1097)):*
> ```C
> static struct resolution {
> 	uint32_t cx;
> 	uint32_t cy;
> ```

Are the names `cx` and `cy` established convention in OBS? I would prefer to use `width` and `height`. Or perhaps there is already an existing struct we could use instead of rolling a new one?
___
*[plugins/caffeine/caffeine-output.c, line 1126 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLZbb89a-vhjfX9xj5:-LVLZbb89a-vhjfX9xj6:b564lmq) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-output.c#L1126)):*
> ```C
> 			darray_push_back(sizeof(struct resolution), d, &res);
> 	}
> 	return d;
> ```

I think this is more complex than necessary and gives more results than desired. I'm thinking something more like:

```
static struct darray *caffeine_scaled_resolutions(uint32_t cx, uint32_t cy)
{
	static uint32_t const HEIGHTS[] = { 360, 720, 1440, 2160, NULL };

	struct darray *d = bmalloc(sizeof(struct darray));
	darray_init(d);
	for (uint32_t * height = HEIGHTS; *height; ++height) {
		struct resolution res;
		res.cy = *height;
		res.cx = cx * (*height) / cy;
		darray_push_back(sizeof(struct resolution), d, &res);
	}
	return d;
}
```
___
*[plugins/caffeine/caffeine-service.c, line 64 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLb8FN9_gyyx1oQTkL:-LVLb8FN9_gyyx1oQTkM:bpvm6cm) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-service.c#L64)):*
> ```C
> 	obs_data_set_bool(requirements, REFRESH_TOKEN_KEY, true);
> 	obs_data_set_bool(requirements, BROADCAST_TITLE_KEY, true);
> //	obs_data_set_bool(requirements, BROADCAST_RATING_KEY, true);
> ```

Remove commented code
___
*[plugins/caffeine/caffeine-service.c, line 79 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLbOXO9Xm_m2MfXVN0:-LVLbOXO9Xm_m2MfXVN1:bjdroh) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-service.c#L79)):*
> ```C
> 	obs_data_set_bool(settings, "disable_prefer_hardware", true);
> 	obs_data_set_bool(settings, "disable_stream_local_testing", true);
> 	obs_data_set_bool(settings, "disable_record_local_testing", true);
> ```

These ones are all at the top level while the others are lumped under `output_settings` and `requirements` ... I think these should be under something as well, e.g. `autoconfig_settings` or something.
___
*[plugins/caffeine/caffeine-service.c, line 180 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLcCFcEUbjAw5dd6PX:-LVLcCFcEUbjAw5dd6PY:b-fyur6a) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-service.c#L180)):*
> ```C
> 	UNUSED_PARAMETER(data);
> 
> 	set_requirements(settings);
> ```

Why does this need to be called here? The requirements don't change based on signed in/out state
___
*[plugins/caffeine/caffeine-service.c, line 252 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLcL-W5iwZjdiTZ_fF:-LVLcL-W5iwZjdiTZ_fG:bp9hdf) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-service.c#L252)):*
> ```C
> 	UNUSED_PARAMETER(data);
> 
> 	set_requirements(settings);
> ```

Same q as above
___
*[UI/window-basic-auto-config.cpp, line 62 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLfdwSExRm9G7IABr7:-LVLfdwSExRm9G7IABr8:bw2vi9p) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config.cpp#L62)):*
> ```cpp
> 		obs_data_item_t *item;
> 		for (item = obs_data_first(videoSettings); item; obs_data_item_next(&item)) {
> 			obs_data_type item_type = obs_data_item_gettype(item);
> ```

Unused variable warning
___
*[UI/window-basic-auto-config.cpp, line 694 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLg5b02L5BrczLXXrW:-LVLg5b02L5BrczLXXrX:b-jh140z) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config.cpp#L694)):*
> ```cpp
> 	blog(LOG_INFO, "%s", json);
> 	for (item = obs_data_first(requirementsObj); item; obs_data_item_next(&item)) {
> 		enum obs_data_type type = obs_data_item_gettype(item);
> ```

unused variable warning
___
*[UI/window-basic-auto-config.cpp, line 797 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLgbYt3TUPpR75yRNy:-LVLgbYt3TUPpR75yRNz:b9t29qe) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config.cpp#L797)):*
> ```cpp
> 	int bitrate = config_get_int(main->Config(), "SimpleOutput", "VBitrate");
> 	streamPage->ui->bitrate->setValue(bitrate);
> 	//streamPage->UpdateBandwidthTest();
> ```

delete commented line
___
*[UI/window-basic-settings.cpp, line 1322 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLhXsl-w3us7YyuNeC:-LVLhXsl-w3us7YyuNeD:b-56grsr) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-settings.cpp#L1322)):*
> ```cpp
> 			ui->advOutFFRescale->addItem(fixedWRes.c_str());
> 		}
> 	}
> ```

The defaults above should only be used if `obs_output_get_scaled_resolutions` returns empty/null.
___
*[UI/window-basic-settings.cpp, line 1324 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVLhQva8iVo6G42jPO4:-LVLhQva8iVo6G42jPO5:b-9ezzak) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-settings.cpp#L1324)):*
> ```cpp
> 	}
> 
> 	struct resolution {
> ```

Move this declaration to header


<!-- Sent from Reviewable.io -->

2019-01-04 19:09 UTC, cogwheel requested changes
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/14)* status: 7 of 10 files reviewed, 16 unresolved discussions (waiting on @Andersama)

___
*[UI/window-basic-auto-config-test.cpp, line 144 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPBtRI2b1R_u-6Z_Wj:-LVPBtRI2b1R_u-6Z_Wk:bx9fef8) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config-test.cpp#L144)):*
> ```cpp
> 		}
> 
> 		if (propertyType == OBS_PROPERTY_LIST) {
> ```

I think the contents of this `if` should be moved to the `case OBS_PROPERTY_LIST` above
___
*[UI/window-basic-auto-config-test.cpp, line 152 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPDD3a42aJ-L97jj9K:-LVPDD3a42aJ-L97jj9L:b-lh1sxk) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config-test.cpp#L152)):*
> ```cpp
> 				servers.emplace_back(wiz->server.c_str(), wiz->server.c_str());
> 				return;
> 			}
> ```

This switch statement can be simplified to `if (comboFormat != OBS_COMBO_FORMAT_STRING) {...}`
___
*[UI/window-basic-auto-config-test.cpp, line 1010 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPE4pY9NvfdJ8z8pCC:-LVPE4pY9NvfdJ8z8pCD:bu4058q) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config-test.cpp#L1010)):*
> ```cpp
> 	}
> 
> 	struct resolution {
> ```

Use shared declaration per other comments
___
*[UI/window-basic-auto-config-test.cpp, line 1026 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPEJv68gaR13OY73Zh:-LVPEJv68gaR13OY73Zi:by1ff3k) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config-test.cpp#L1026)):*
> ```cpp
> 	/* Pick closest of service specified resolutions (if any) */
> 	if (output_resolutions) {
> 		int bestPixelDiff = 0x7FFFFFFF;
> ```

Use `std::numeric_limits<int>::min()` instead of hard-coded value.


<!-- Sent from Reviewable.io -->

2019-01-04 21:21 UTC, cogwheel requested changes
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/14)* status: 6 of 10 files reviewed, 17 unresolved discussions (waiting on @Andersama)

___
*[plugins/caffeine/caffeine-service.c, line 72 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPHCFt8TGNbNXYa24A:-LVPHCFt8TGNbNXYa24B:byqa7v1) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/plugins/caffeine/caffeine-service.c#L72)):*
> ```C
> 	obs_data_set_int(output_settings, "output_fps_den", 1);
> 	obs_data_set_bool(output_settings, "output_prefer_high_fps", false);
> 	obs_data_set_obj(settings, "output_settings", output_settings);
> ```

I think all of these toplevel settings should be marked as transient so they don't get stored in user preferences and thus respond to updates


<!-- Sent from Reviewable.io -->

2019-01-04 21:24 UTC, cogwheel requested changes
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/obs-studio/14)* status: 6 of 10 files reviewed, 17 unresolved discussions (waiting on @Andersama)

___
*[UI/window-basic-auto-config-test.cpp, line 1026 at r1](https://reviewable.io/reviews/caffeinetv/obs-studio/14#-LVPEJv68gaR13OY73Zh:-LVPkBih38dyvBccIlfw:b-wu01b6) ([raw file](https://github.com/caffeinetv/obs-studio/blob/dd0cd2ffdafe125f9c25ed1a4b09c57daba1b8e7/UI/window-basic-auto-config-test.cpp#L1026)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Use `std::numeric_limits<int>::min()` instead of hard-coded value.
</blockquote></details>

Err that's `max` not `min`.


<!-- Sent from Reviewable.io -->

2019-01-04 22:30 UTC, Andersama commented
The struct could definitely belong in a header. If you're going to use a darray for the heights you could use the size of the array for iteration.

From what I remember I was having difficulty getting settings to stick around, so on update I had them set. Didn't go back over it though, so they probably could be better placed.

Unused variable warning stuff can go, commented line can definitely go. Transient settings should be fine, actually and w/ that most of the logging I did in testing can be changed to something like LOG_DEBUG. 

And as for settings, up to you, I think originally I had this where the blocks of code were wrapped in an else if, giving one set of results from OBS's method only if no results were found, and then there's the other option of having all the ones merged together.

I kept the auto-config window setup to use the preferred resolutions if any were listed.

2019-04-19 00:55 UTC, cogwheel commented
This was merged/rebased in other ways

2019-04-19 00:55 UTC, closed without merging